Using TensorFlow backend.
Traceback (most recent call last):
  File "label_video_objects.py", line 19, in <module>
    from videosequence import VideoSequence
ImportError: No module named 'videosequence'
2018-11-10 19:37:20.379435: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-10 19:37:20.379796: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-10 19:37:20.379811: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Using TensorFlow backend.
Downloading pretrained model to /nfs/users2/rg/ramador/Citython_2018/citython_bcn/people_counting/mask_rcnn_coco.h5 ...
... done downloading pretrained model!
Traceback (most recent call last):
  File "label_video_objects.py", line 133, in <module>
    person_blocker(args)
  File "label_video_objects.py", line 81, in person_blocker
    reader = imageio.get_reader(args.image)
  File "/users/rg/ramador/.conda/envs/Cython/lib/python3.4/site-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "/users/rg/ramador/.conda/envs/Cython/lib/python3.4/site-packages/imageio/core/format.py", line 174, in get_reader
    return self.Reader(self, request)
  File "/users/rg/ramador/.conda/envs/Cython/lib/python3.4/site-packages/imageio/core/format.py", line 224, in __init__
    self._open(**self.request.kwargs.copy())
  File "/users/rg/ramador/.conda/envs/Cython/lib/python3.4/site-packages/imageio/plugins/ffmpeg.py", line 346, in _open
    self._exe = self._get_exe()
  File "/users/rg/ramador/.conda/envs/Cython/lib/python3.4/site-packages/imageio/plugins/ffmpeg.py", line 291, in _get_exe
    cls._exe = cls._exe or get_exe()
  File "/users/rg/ramador/.conda/envs/Cython/lib/python3.4/site-packages/imageio/plugins/ffmpeg.py", line 127, in get_exe
    "Need ffmpeg exe. "
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can obtain it with either:
  - install using conda: conda install ffmpeg -c conda-forge
  - download using the command: imageio_download_bin ffmpeg
  - download by calling (in Python): imageio.plugins.ffmpeg.download()

